### ISSUE TITLE
Split the PRIVCOUNT event into separate event types in PrivCount

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#100]
Once #99 is implemented, each round, we want to ask for the event types in PrivCount based on the counters we are being asked to collect. We also need to modify the TorControlServerProtocol stub to handle each event type.

**Comment by robgjansen** [comment]
#99 is done, see my comment there for some details.

**Comment by teor2345** [comment]
A good implementation here will be table-driven: each counter uses one (or more?) events, and the events we want are the union of all the events required by all the active counters.

**Comment by teor2345** [comment]
This also means updating the injector data for the unit tests.

**Comment by teor2345** [comment]
@robgjansen is each PrivCount counter documented somewhere?
Is there a mapping between each counter and the event(s) it uses?
Does each counter only depend on one event, or do some counters use multiple events?
If not, might some counters use multiple events in future?

**Comment by robgjansen** [comment]
> is each PrivCount counter documented somewhere?

The best place for this was in `counters.*.yaml`. I never created a separate file to document them, though that would certainly make sense.

> Is there a mapping between each counter and the event(s) it uses?

Again, there is currently no document listing an explicit mapping. It has been easiest for me to just look at the aggregator code in `data_collector.py`, since it was changing often and never very complicated, as opposed to try to keep another document in sync with the many code changes. Perhaps we have now reached a stable point where that no longer holds.

The counter names generally indicate the point at which the counters are incremented:

  + counters whose names begin with *Stream* are incremented on a *stream end* event in `_handle_stream_event`;
  + counters whose names begin with *Circuit* are incremented on a *circuit end* event in `_handle_circuit_event`;
  + counters whose names begin with *Connection* are incremented on a *connection end* event in `_handle_connection_event `;
  + counters whose names begin with *ClientIP* are incremented periodically every 10 minutes in `_do_rotate `;

> Does each counter only depend on one event, or do some counters use multiple events?
> If not, might some counters use multiple events in future?

Yes, counters may rely on multiple events.

  + The *ClientIP* family of counters depend on the *circuit end* event being enabled.
  + These depend on the *stream end* event being enabled:
    + CircuitsAll
    + CircuitsActive
    + CircuitsInactive
    + CircuitLifeTime
    + CircuitStreamsAll
    + CircuitInterStreamCreationTime
    + CircuitsWeb
    + CircuitStreamsWeb
    + CircuitInterStreamCreationTimeWeb
    + CircuitsInteractive
    + CircuitStreamsInteractive
    + CircuitInterStreamCreationTimeInteractive
    + CircuitsP2P
    + CircuitStreamsP2P
    + CircuitInterStreamCreationTimeP2P
    + CircuitsOther
    + CircuitStreamsOther
    + CircuitInterStreamCreationTimeOther

(I noticed that *CircuitLifeTime* should really be called *CircuitLifeTimeActive*, and then we should add *CircuitLifeTimeAll* and *CircuitLifeTimeInactive* as new counters - I've opened #128 for this.)

**Comment by teor2345** [comment]
> > Is there a mapping between each counter and the event(s) it uses?

> Again, there is currently no document listing an explicit mapping. It has been easiest for me to just look at the aggregator code in data_collector.py, since it was changing often and never very complicated, as opposed to try to keep another document in sync with the many code changes. Perhaps we have now reached a stable point where that no longer holds.

No, I don't think we need a document, a data structure used to look up the required events will be sufficient documentation, particularly if it is well-formatted:

> A good implementation here will be table-driven: each counter uses one (or more?) events, and the events we want are the union of all the events required by all the active counters.

**Comment by teor2345** [comment]
There appear to be no counters which depend on the following events:
PRIVCOUNT_DNS_RESOLVED
PRIVCOUNT_STREAM_BYTES_TRANSFERRED

**Comment by teor2345** [comment]
I have updated the event parsing, but I still need to write code (and a table) that:
* selects the PrivCount events based on the counters in each round (the table)
* sends a SETEVENTS at the start of each round with these events
  * every time a new round starts, the events may change
  * test_tor_ctl_port.py should ask for all events
  * the injector should respect the events sent
  * the client should filter events out if they aren't in the latest set
  * every time the control port client reconnects, it will need to ask for the latest events
  * every time a round finishes, the events should be turned off

**Comment by robgjansen** [comment]
`PRIVCOUNT_DNS_RESOLVED` was inherited from PrivEx, but we don't currently use it.
`PRIVCOUNT_STREAM_BYTES_TRANSFERRED` is used in my branch for #19, which will be merged at some point.

**Comment by teor2345** [comment]
We might even want to turn off the PrivCount option every time a round ends, and turn it on again when the round starts.

**Comment by teor2345** [comment]
(That would save users from having to remember, and provide a consistent method for determining whether tor was compiled with PrivCount support.)

**Comment by teor2345** [comment]
Split "the injector should respect the events sent" into #141.

**Comment by teor2345** [comment]
I have a draft branch:
https://github.com/teor2345/privcount/tree/split-event-v3

I still need to change the code so it:
* selects the PrivCount events based on the counters in each round (the table)

**Comment by teor2345** [comment]
> These depend on the stream end and the circuit end events being enabled:
> * CircuitsAll
> ...
> * CircuitLifeTime

Not quite, they only depend on the circuit end, because they are updated regardless of the stream information.

**Comment by teor2345** [comment]
I needed to finish #130 to finish this, because the import dependencies became unmanageable
