### ISSUE TITLE
Test all possible counters

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#110]
Some counters are missing from our test configs.
It would be a good idea to test all counters, in both sigma and automatic noise calculation modes.

**Comment by teor2345** [comment]
Moving this to 0.2.0: I think we need to do this so we can make sure we haven't broken any counters when fixing #191.

**Comment by teor2345** [comment]
Actually, make this 0.2.1, but @robgjansen, I need you to check that the current set of tested counters are the ones we want to use for the 0.2.0 deployment.

**Comment by robgjansen** [comment]
I think the most updated list of counters is here:
https://github.com/privcount/privcount/blob/master/test/counters.noise.yaml

It's a bit hard manually inspect what is missing since PrivCount doesn't output a list of all counters it supports. However...

```
cat privcount/data_collector.py  | grep -e "Stream" -e "Circuit" -e "Sanity" -e "ClientIP" | cut -d'"' -f2 | sort | grep -v "#" > supported
cat test/counters.noise.yaml | grep -e "Stream" -e "Circuit" -e "Sanity" -e "ClientIP" | cut -d'"' -f2 | cut -d':' -f1 | cut -d' ' -f5 | sort > tested
diff --new-line-format="" --unchanged-line-format=""  supported tested
```

Shows us the 12 counters that are supported but not tested:

```
CircuitInterStreamCreationTimeP2P
CircuitsActiveEntry
CircuitsAllEntry
CircuitsInactiveEntry
CircuitsP2P
CircuitStreamsP2P
StreamBytesInP2P
StreamBytesInteractive
StreamBytesOutP2P
StreamBytesP2P
StreamBytesRatioP2P
StreamLifeTimeP2P
StreamsInteractive
StreamsP2P
```

These are the most useful:

```
CircuitsActiveEntry
CircuitsAllEntry
CircuitsInactiveEntry
```

but my plan for v0.2.0 is to focus on just the traffic model, so I think this can all wait until v0.2.1.

---

And then also the traffic modeling counters. The actual labels are dynamic depending on the traffic model input file, but there are 9 of "types" listed here:
https://github.com/privcount/privcount/blob/master/test/traffic.noise.yaml

Those are all currently tested so we should be OK.

**Comment by teor2345** [comment]
Some counters contain "Connection":
```
cat privcount/data_collector.py  | grep -e "Stream" -e "Circuit" -e "Sanity" -e "ClientIP" -e "Connection" | cut -d'"' -f2 | sort | grep -v "#" > supported
cat test/counters.noise.yaml | grep -e "Stream" -e "Circuit" -e "Sanity" -e "ClientIP" -e "Connection" | cut -d'"' -f2 | cut -d':' -f1 | cut -d' ' -f5 | sort > tested
diff --new-line-format="" --unchanged-line-format=""  supported tested
```
I see 15:
```
CircuitInterStreamCreationTimeP2P
CircuitStreamsP2P
CircuitsActiveEntry
CircuitsAllEntry
CircuitsInactiveEntry
CircuitsP2P
ConnectionLifeTime
StreamBytesInP2P
StreamBytesInteractive
StreamBytesOutP2P
StreamBytesP2P
StreamBytesRatioP2P
StreamLifeTimeP2P
StreamsInteractive
StreamsP2P
```

**Comment by teor2345** [comment]
We can't do a mass rename without checking that it worked.
