### ISSUE TITLE
Prevent counter overflow

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#18]
Counts are currently stored as `float` types but should be stored as `long` types. We've seen overflow issues with float when counts get too high.
https://github.com/robgjansen/privcount/blob/d538dfdfe3721898de8b43ee532d7566714b8fa4/privcount/util.py#L216

I', not sure if the `q` parameter should also be stored as a long after reading it from the config file:
https://github.com/robgjansen/privcount/blob/d538dfdfe3721898de8b43ee532d7566714b8fa4/privcount/tally_server.py#L177

We should stop scaling bytes to kilobytes once we are using long to prevent overflow issues:
https://github.com/robgjansen/privcount/blob/d538dfdfe3721898de8b43ee532d7566714b8fa4/privcount/data_collector.py#L342

It may be useful to start with a test case using `test/test_counters.py` that shows the overflow problem, to ensure that using long values will fix it.

**Comment by teor2345** [comment]
master has moved on since this ticket was written. I have edited Rob's original links to reference the source files as they were on 16 July 2016.

**Comment by teor2345** [comment]
In python (including its yaml import implementation), if a number contains a decimal point, it is typed float, which typically has the machine's C double precision (sys.float_info).

Otherwise, it is typed int, which typically has at least 32 bits of precision (sys.maxint).

If a number is suffixed with 'L' (or 'l'), it is an unlimited-precision python long. Python's type widening is also supposed to create longs when results are too large for an int, but I wouldn't want to rely on that: it's safer to just cast everything to long (using the constructor 'long()' or suffix 'L') as soon as we import or declare it.

Given that the type precedence in python widens from int to long to float to complex, we should avoid using int entirely for counters. And we should use float when we need fractional counts, or infinities.

https://docs.python.org/2.7/library/stdtypes.html#typesnumeric

It seems that sigmas are floating point, so I wondered what the impact was of rounding added counter noise to integer values, but we already do `int(round(sampled_noise))`.

We need to keep the bin boundaries as float, because they are potentially fractional or infinite.

For consistency, bin counters should be longs, which implies that q should be a long, too, as it's used as a modulus for counts.

Abstracting the counter conversions to long into a single utility function would be useful to check that we've resolved this issue.

**Comment by teor2345** [comment]
I can confirm that the current float counter implementation can not accurately count 1 increment when q is approximately 2**53. This does not affect the current implementation, as q is ~2**40.

Here's the test_counters.py code I used for testing, I'll use it to test the privcount changes that fix this issue, and merge it into the counter fix branch:
https://github.com/teor2345/privcount/tree/test-counter-overflow-v2

**Comment by teor2345** [comment]
Updated the test branch to check for secret and blinding value collisions - this is a precaution against obvious failures, not a guarantee that the construct is correct.

**Comment by teor2345** [comment]
Counters can still overflow if they're passed a double - we should cast everything to long before adding it to the counter.
