### ISSUE TITLE
Add enforced delay between collection with different noise values

### ISSUE THREAD

**Issue by ajohnson-nrl** [privcount/privcount#22]
Changing the noise allocation across statistics should require some delay that is set during initialization. The noise allocation can change for a few reasons, including changing the set of statistics being collected and changing the estimated values for those statistics. To provide differential privacy for a certain amount of activity within a certain amount of time t, no SK should allow a collection to proceed with new noise values (aka sigmas) unless t time has passed since the last collection ended.

**Comment by teor2345** [comment]
If the noise allocation doesn't change:
* the SKs should allow the next round without any delay.
If the noise allocation changes:
* the SKs should enforce a configurable delay between rounds (based on a config option set with the noise parameters)
  * the TS would need to tell the DCs and the SKs the noise allocation
    * this means that we need to do #9 first, before this ticket
  * the SKs need to check that if the noise allocation has changed from the previous round, that round was at least the configured interval ago

**Comment by teor2345** [comment]
Since #9 re-calculates the noise values each time, we should have a tolerance for the amount of change in noise values:
* if the noise values have only increased
* if the noise values have only decreased by a configurable proportion (ideally between 1/2**10 and 1/2**53, default to 1/2**20)

**Comment by teor2345** [comment]
The delay and noise tolerance need to be documented in a doc/ directory.

**Comment by teor2345** [comment]
Implementation notes:

The round should fail if the TS:
* specifies overlapping bins (#75)

The round should be delayed (that is, should fail if the configured interval has not elapsed since the last successful round) if the TS:
* changes the set of counters
* changes the estimated values for the counters
* decreases the sigma values beyond the tolerance

Since we convert float values to base 10 for transmission, we can't guarantee any more than `10**(sys.float_info.dig)` precision, which is `10**15` on most 64-bit hardware.

Default sigma decrease tolerance: `10**(sys.float_info.dig)`
Warn if sigma decrease tolerance is less than: `10**(sys.float_info.dig)`
Config error if sigma decrease tolerance is less than: `2**(sys.float_info.mant_dig)` (`2**53` on most 64-bit hardware)
Warn if sigma decrease tolerance is greater than:
Config error if sigma decrease tolerance is greater than: 

It is possible to decrease the sigmas by the configured tolerance by running a short, successful round. If this round is shorter than the enforced delay, it is possible to decrease the noise values multiple times within the enforced delay period. (It only takes 10-20 seconds to run an empty PrivCount round.) Therefore, the SKs also need to ensure that the collect_period is greater than or equal to the enforced delay.

Alternately, the SKs could compare the TSs proposed sigmas against the values for the first successful round after the last delay.

**Comment by teor2345** [comment]
This depends on branch #115

**Comment by teor2345** [comment]
The enforced delay should also resist message replay attacks - so it is important that all nodes refuse to believe messages with timestamps from previous rounds. (Do messages have timestamps already?)

**Comment by teor2345** [comment]
When the SKs impose this enforced delay, the TS should react gracefully, and wait, rather than trying to re-initiate the round every second.

**Comment by teor2345** [comment]
My branch
https://github.com/teor2345/privcount/tree/enforced-delay
has a work-in-progress version where the TS enforces the delay.
It passes the new unit tests in #126, and fixes a DC bug in #125.

I still need to:
* add a configurable option to always impose a delay
* add a configurable tolerance for sigma decreases
* add checks to the SKs (and, although it's somewhat redundant, DCs)
* document the enforced delay in the docs/ directory, and maybe the README?
  * split off into #127

**Comment by teor2345** [comment]
Because of the changes I made in #122, this branch will no longer merge without conflicts.
I will rebase once #122 merges.

**Comment by teor2345** [comment]
This is implemented in pull request #131
