### ISSUE TITLE
The Client IP counts always increment the "1" bin

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#283]
Aggregator._do_rotate is called with a different aggregator object to the object used by the data collector.

**Comment by teor2345** [comment]
That's not right, I'm running multiple data collectors.
There's some error happening in do_rotate that gets swallowed because the Deferred has no Errback. It's an instance of #47.

**Comment by teor2345** [comment]
We were incrementing the "1" bin by the number of ClientIPs.
I think what was intended was to increment the "number of ClientIPs" bin once.

**Comment by teor2345** [comment]
This affects the EntryClientIPCount, EntryActiveClientIPCount, and EntryInactiveClientIPCount.

**Comment by teor2345** [comment]
@robgjansen, were these meant to be single-bin counters?

**Comment by robgjansen** [comment]
Like #276, these were all meant to be single-bin counters. See table 9 in [the privcount paper](http://www.robgjansen.com/publications/privcount-ccs2016.pdf).

The problem seems to be that I overloaded the single-counter and bin-counter types to use the same config format and the same internal object and code to do the counting. Perhaps there is an easy refactoring that could make that more clear in the code. Again, sorry for the confusion!

**Comment by teor2345** [comment]
> The problem seems to be that I overloaded the single-counter and bin-counter types to use the same config format and the same internal object and code to do the counting. 

The config format and function call are the most confusing parts of this.
Using the same code internally is good design: much better than writing similar code twice.

> Perhaps there is an easy refactoring that could make that more clear in the code.

Yes, see my existing commit in pull #286, which makes the counter type obvious, and asserts if it doesn't match the bin config: https://github.com/privcount/privcount/pull/286/commits/52d3c395b46f5ec5a902a40104905fbc33abb829

I'll fix the bin configs and function calls so they are single-bin counters.
