### ISSUE TITLE
Avoid the traffic model being O(bandwidth) in both time and space

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#292]
Hi @robgjansen,

The traffic model builds a list of packets in a loop, based on the amount of data in a bandwidth event:
https://github.com/privcount/privcount/blob/master/privcount/traffic_model.py#L278

This is going to cause trouble during my load testing, when I send max-length data events.

Is there some reasonable upper bound on the number of packets this code should generate?
(For example, 100 or 1000?)

Can multiple full-length, zero-delay packets be coalesced into a single increment?

Is there some other design that still achieves a similar result without a loop and a list?

**Comment by teor2345** [comment]
> Is there some reasonable upper bound on the number of packets this code should generate?
> (For example, 100 or 1000?)

See my commit 1efa269 for a basic fix that limits the number of simulated packets to 100.

I tried 10,000, but that took so long that the aggregator ended up dropping out of the network.
And I think 1000 is too large, because that means we potentially allocate 10s of kilobytes of memory per bandwidth event. (We could reduce this by using integers rather than strings for directions, see #294.)

**Comment by teor2345** [comment]
I did some testing using chutney today on the 2-state traffic model (oops!). This is how long it takes the simple traffic model to process a single stream:
```
30 seconds to process 299221 packets (400 MB or 11 seconds at 300Mbps )
11 seconds to process 149933 packets (200 MB or 5.3 seconds at 300Mbps )
4.0 seconds to process 75054 packets (100 MB or 2.7 seconds at 300Mbps)
1.6 seconds to process 37659 packets (50 MB or 1.3 seconds at 300Mbps)
0.7 seconds to process 18775 packets (25 MB or 0.7 seconds at 300Mbps)
0.4 seconds to process 9372 packets (13 MB or 0.3 seconds at 300Mbps)
```
So it's slightly more than linear (packets x 2 -> time x 3), and it gets more exponential the bigger the data gets.

With the traffic model you emailed me, the timings for increment_traffic_counters() are:
```
10 seconds to process 18837 packets (25 MB or 0.7 seconds at 300Mbps)
4.9 seconds to process 9387 packets (13 MB or 0.3 seconds at 300Mbps)
2.5 seconds to process 4693 packets (6 MB or 0.2 seconds at 300Mbps)
1.2 seconds to process 2347 packets (3 MB or 0.1 seconds at 300Mbps)
0.6 seconds to process 1172 packets (1.6 MB or 0.04 seconds at 300Mbps)
0.36 seconds to process 589 packets (0.8 MB or 0.02 seconds at 300Mbps)
0.16 seconds to process 296 packets packets (0.4 MB or 0.01 seconds at 300Mbps)
0.12 seconds to process 202 packets (0.2 MB or 0.007 seconds at 300Mbps)
0.04 seconds to process 74 packets (100 kB or 0.003 seconds at 300Mbps)
0.02 seconds to process 38 packets (50 kB or 0.001 seconds at 300Mbps)
0.014 seconds to process 19 packets (25 kB or 0.007 seconds at 300Mbps)
```
The algorithm is O(packet_count * state_count * previous_state_count), so when you added more states, the times blew out.

We're very close to reaching CPU starvation, regardless of the actual traffic distribution. (We know that 6% of our traffic is in > 64KB streams.) I've also not measured any processing times that are *less* than the amount of time it takes to send that much data at 300 Mbps, which is worrying.

A single 100 MB stream would probably cause a checkin failure. And I bet we'd start dropping control port events as soon as delays go above a few seconds - which could happen every time we get a ~3MB stream during the week we collect.

I'm doing this testing on a local macOS VM. There are many more overheads on an actual exit. Our exits could be faster or slower, either due to OS, RAM, or CPU. It's hard to say. I'm happy to run some tests if you'd like. But I think they won't be much different.

I've added some warnings so we know when they're happening.

But you might end up having to revise either the traffic model itself, or the code, so it is more efficient.

**Comment by robgjansen** [comment]
We could move the code that turns 'bytes' into 'packets' into Tor, and have Tor emit the packet events instead of the bytes events. I think we could make it more efficient that way, but there might still be a lag at the end of the stream due to a spike in processing...

**Comment by robgjansen** [comment]
> Can multiple full-length, zero-delay packets be coalesced into a single increment?

Yes, I don't see why this shouldn't be possible as long as the same overall increments are happening here:
https://github.com/privcount/privcount/blob/master/privcount/traffic_model.py#L338

Although, it does look like this counter needs to get incremented for each packet, since the 'next state' could potentially change after every packet:
https://github.com/privcount/privcount/blob/master/privcount/traffic_model.py#L356

> Is there some other design that still achieves a similar result without a loop and a list?

Yeah, probably. I wrote the proof of concept so long ago to quickly get functional code.

**Comment by robgjansen** [comment]
So, after some more thought, I don't think we can increment any counters continuously throughout the lifetime of the stream, because I think we need to run the viterbi algorithm in `run_viterbi` with the full set of packet observations so that it can compute the most probably path through the model. This is probably the most computationally intensive part of counting a model, and it happens when each stream ends.

However, I do think we can be smarter about how we store bytes events and turn those into packets in `_get_inter_packet_delays`.

We need to track chunks of bytes, called 'packets', as they are sent on a stream over time. A packet item can simply be represented by a collection of say 1500 bytes, traveling in a direction, at a given time delay since the previous packet was transferred.

We could also include a count with each item stored in memory to avoid creating another item if the direction and delay are the same. Then we have a list of these items ordered by the time the packets were sent (i.e., new packets get appended), which is important for movement through the model.

That would give us a list of "packet bundles", for example:

observ = [
(dir='+', delay=50, count=1),
(dir='-', delay=100, count=1),
(dir='-', delay=0, count=31),
(dir='+', delay=50, count=1),
(dir='+', delay=0, count=2),
(dir='-', delay=100, count=1)
]

When a stream ends, [the viterbi algorithm](https://github.com/privcount/privcount/blob/master/privcount/traffic_model.py#L192) gets run on the full set of observations. If we store the packets as above, we no longer have the full set, so we would have to write a `get_packet()` function that can return the correct 'packet' given an index. So, for example, `get_packet(observ, 5)` would return `(dir='-', delay=0)`, i.e., one of the packets that were packed into this line: `(dir='-', delay=0, count=31),`.

We could maintain the list above over time instead of calling `_get_inter_packet_delays` at the end of the stream. This will at least limit the overhead at the end of a stream to the running of the viterbi algorithm.

We could also keep sending bytes events from Tor to PrivCount as is currently implemented, or we could remove the byte event and instead have Tor do the logic of creating the items in the above list, i.e. the "packet bundles". Then Tor could emit those packet bundle events one at a time during the lifetime of the stream, and each can be emitted as soon as we are certain that the next bytes would require a new packet bundle.

PrivCount *cannot* immediately increment the correct counters the appropriate number of times based on the item details rather than storing them in memory, though, because we need to run viterbi on the full list of packets from a stream.

**Comment by robgjansen** [comment]
I'm wondering if the bytes events that are sent from Tor to PrivCount are causing performance problems? Or are we primarily concerned with the handling of those events inside of PrivCount?

---

We might consider running viterbi in a separate thread/process, adding the result to a queue, and then the main thread could increment those results in a future main loop run.

**Comment by teor2345** [comment]
> I think we need to run the viterbi algorithm in run_viterbi with the full set of packet observations so that it can compute the most probably path through the model. This is probably the most computationally intensive part of counting a model, and it happens when each stream ends.

> PrivCount cannot immediately increment the correct counters the appropriate number of times based on the item details rather than storing them in memory, though, because we need to run viterbi on the full list of packets from a stream.

> We might consider running viterbi in a separate thread/process, adding the result to a queue, and then the main thread could increment those results in a future main loop run.

Is the viterbi algorithm inevitably O(packets * states * previous_states)?
If we can't reduce the number of packets, reducing the number of states by about 10x would help.

Or we could improve the algorithm so it's 10x faster, and run it on another core.
(Do all our relays have 1 spare core per data collector, after tor and tor's cpuworkers and privcount? They certainly don't have 10 spare cores per tor instance.)

Or we could improve the algorithm so it's 100x faster, and run it single-threaded.

Or we could limit the traffic on each relay to 1/10.
We could add more relays to compensate, but I don't think this is at all feasible (or a representative sample, for that matter).

> We could move the code that turns 'bytes' into 'packets' into Tor, and have Tor emit the packet events instead of the bytes events. I think we could make it more efficient that way, but there might still be a lag at the end of the stream due to a spike in processing...

This make the bytes events about 300 characters rather than 70 characters. It could make parsing slower, so it's not the first thing I'll try. Also, this part of the code is O(packets), so it is much less likely to be the cause of the issue.

The same analysis applies to the list, it is only O(packets), so it is much less likely to be the cause of the issue. But using a list of single integers might still be a performance improvement over using a list of tuples.

I'll do some measurements and see which parts of the code are slow.

**Comment by teor2345** [comment]
Here is the timing breakdown for the 3MB case:

1.342 seconds to process 2252 packets
Breakdown: packet 0.003 viterbi 1.278 counter 0.061.

Remember, at 300Mbps, sending 3MB takes 0.076 seconds.
So we might not even have enough CPU to increment 9 counters per packet, regardless of the number of states in the model or any other factors.

**Comment by teor2345** [comment]
> Remember, at 300Mbps, sending 3MB takes 0.076 seconds.
> So we might not even have enough CPU to increment 9 counters per packet, regardless of the number of states in the model or any other factors.

But that won't matter unless we get the viterbi runtime down to a similar figure.
(And if we could do that, I'd run it on a relay and hope it was just fast enough.)

**Comment by teor2345** [comment]
Deferring to 1.1.0 as discussed by email.

**Comment by teor2345** [comment]
I did some testing on a relay. The processing speed is almost identical to the figures I quoted above for my laptop. That said, the collection process itself seemed to survive. But I'm not sure if any events were dropped.

**Comment by teor2345** [comment]
arma has confirmed for me that there is no longer any maximum output buffer size, so the limit on the control port backlog is either available RAM or Tor's OOM killer.

(The limit was removed in 0.2.7.3-rc in https://bugs.torproject.org/16480 , and PrivCount 1.0 will be on 0.2.9.10 at the earliest.)

So as long as the DC keeps processing events and sending checkins, everything will work. If the DC falls behind by ~7 checkin periods, the TS will declare the DC dead and the round will fail.

**Comment by teor2345** [comment]
We will fix this if it becomes an issue during the collections we run.

**Comment by teor2345** [comment]
@robgjansen, how do you want to merge your issue292 branch to master?

**Comment by robgjansen** [comment]
Good question! I've sort of been fixing some minor bugs as I encounter them and not doing a great job of linking my work to the issue tracker. (Like for example I added some new single counters counting exit bytes for completeness, and renamed some existing counters to designate that they are histograms, but didn't link that work to any issues.) If you are OK with that, then I would be happy to rebase and merge now or after you review the branch. Perhaps it would be a good idea to squash it too, but it probably doesn't matter too much and since this is research code we should probably lean toward whatever is fastest.

**Comment by teor2345** [comment]
I merged this branch into master, and added some unit test fixes.

**Comment by teor2345** [comment]
This is a breaking change, because it renames counters. So the next release will be called 2.0.0.

**Comment by robgjansen** [comment]
In that case, while we are at it should we also rename the rest of the `...Count` labels that should actually be `...Histogram`?

**Comment by teor2345** [comment]
> In that case, while we are at it should we also rename the rest of the ...Count labels that should actually be ...Histogram?

Yes, see #450.
Would you like to do it @robgjansen, or should I?

**Comment by robgjansen** [comment]
Please go ahead @teor2345, if you don't mind.
