### ISSUE TITLE
Configure noise weight in the deployment document

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#44]
Split off from #27.

The noise weight varies among the DCs:
- some DCs are bigger than others
- we want to survive a certain number of machine compromises

The SKs are configured with a noise weight at initialisation.
The DCs use the noise weight in the deployment document and the sigma value in the configuration document to calculate the noise.

The noise weight will be checked for consistency as part of the deployment document checks.
The sigma values will be checked for consistency as part of the configuration document checks.

**Comment by teor2345** [comment]
The consistency checks for the noise weight need to be documented in a doc/ directory.

**Comment by teor2345** [comment]
@ajohnson-nrl, here is my proposed design:
* the TS takes a config option noise_weight that contains a mapping from DC fingerprint to noise weight
  * this option can be an embedded dict or a file, like the counters option
  * We don't currently list DCs, this adds a pre-configured DC list as a requirement
  * The aggregator would get the list of DCs before it looks up the fingerprint, then use the noise weight for its DC
*  the TS sends these weights to the SKs and DCs at initialisation
  * the SKs check these weights
* the DCs use the weight assigned to them to create their aggregator
  * (and, in #9, they use it to calculate sigmas)

Can you comment on these implementation details?
* Is it ok to add a requirement that we pre-configure a list of DCs?
* If there is no weight for its fingerprint, or if the weight is 0.0, what should the DC do?
  * Stop participating?
  * Use 1.0 as a default? This hides failures, so I don't think it's a good idea, unless we want to avoid pre-configuring a list.
  * Calculate the weight somehow?
* What checks should the SKs do on the noise weight?
  * Is checking that the individual values are >= 0.0 and sum is >= 1.0 enough?

**Comment by teor2345** [comment]
@ajohnson-nrl, is this what you wanted?

**Comment by ajohnson-nrl** [comment]
To answer your questions:

"Is it ok to add a requirement that we pre-configure a list of DCs?"

I'm not sure what you mean by "pre-configure", but the TS will need to include a list of DCs in the deployment document.

"If there is no weight for its fingerprint, or if the weight is 0.0, what should the DC do?"

Yeah, DC failure seems like the right choice here.

"What checks should the SKs do on the noise weight? Is checking that the individual values are >= 0.0 and sum is >= 1.0 enough?"

A sanity check that the noise weight is >= 0 seems fine. We then can just assume that the SK operator will check that the noise weights provide sufficient security against malicious DCs. It would be a bit hard to guide the SK operator further in the decision, because he could have several different types of requirements on DCs, such as that a certain number are honest, a certain number of DC *machines* are honest, or that a certain DC *consensus weight* is honest.

**Comment by teor2345** [comment]
#98 has been revised to implement DC failure if the fingerprint is missing, and remove the sum >= 1.0 check.

I have no further questions about this change.

I'm happy for @robgjansen to review and merge, or @ajohnson-nrl to do another review, or I could merge it myself.
