### ISSUE TITLE
How should PrivCount round noise?

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#71]
@ajohnson-nrl, PrivCount currently rounds the sampled noise to the nearest integer, within the limits of floating point inaccuracy. This means that if the intended noise is between:

(-a, +a), where a is a real number

The actual noise values are between:

[-ceil(a), -floor(a), ... , -1, 0, 1, ... , floor(a), ceil(a)]

Does this mean we're adding slightly more (or slightly less) noise than intended?
Does this affect the sigma calculations?

**Comment by ajohnson-nrl** [comment]
The noise is intentionally rounded before adding to handle floating-point issues when generating differentially-private noise [0], which works because the function values are integers.

[0] On Significance of the Least Significant Bits For Differential Privacy, <https://www.microsoft.com/en-us/research/wp-content/uploads/2012/10/lsbs.pdf <https://www.microsoft.com/en-us/research/wp-content/uploads/2012/10/lsbs.pdf>>

**Comment by teor2345** [comment]
@ajohnson-nrl, I've read the paper, but I'm having trouble understanding:
* why the PrivCount mechanism produces differentially private noise (rounding the noise to the nearest integer, then adding it);
* how it's different from the "false start" of rounding the lower bits of the floating point noise (paper section 5.1),
* why the PrivCount mechanism seems so much simpler than the differentially private snapping mechanism (paper section 5.2).

I don't need to understand all the details of this - and I don't want to take up too much of your time.

What I'm trying to work out is if there are limits on the amount of noise we can safely sample in the noise() function in util.py.
That is, does the double-sample-then-integer-round mechanism break down somehow when:
* the sigma_i value is low?
  * for example, all sigma_i values less than 0.5 yield 0 noise when rounded to integers. I think this is ok, but is there some kind of sanity check we should be doing that the calculated sigmas aren't too low in #9 ?
* the sigma_i value is high?
  * for example, if sigma_i is greater than 2**52, any sampled noise values between 2**52 and 2**53 will be even, any sampled noise values between 2**53 and 2**54 will be divisible by 4, and so on. (Doubles have a precision of 2**53, meaning there are exactly 2**52 doubles in each interval [2**N, 2**(N+1)].) Is this a problem?

Do we ever intend to sample noise greater than 2**53?

**Comment by torps** [comment]
> @ajohnson-nrl <https://github.com/ajohnson-nrl>, I've read the paper, but I'm having trouble understanding:
> 
> why the PrivCount mechanism produces differentially private noise (rounding the noise to the nearest integer, then adding it);
> how it's different from the "false start" of rounding the lower bits of the floating point noise (paper section 5.1),
> why the PrivCount mechanism seems so much simpler than the differentially private snapping mechanism (paper section 5.2).
> I don't need to understand all the details of this - and I don't want to take up too much of your time.
> 
You might notice that the “false start” acknowledges that if the change in the values due to a single user’s input is always at least one, then simple rounding is sufficient. It gives an example about rounding isn’t sufficient if the change in the value has a smaller value than the rounding granularity. However, because our values are all integers, they change by at least one for each user, and so rounding is sufficient for us.
> What I'm trying to work out is if there are limits on the amount of noise we can safely sample in the noise() function in util.py.
> That is, does the double-sample-then-integer-round mechanism break down somehow when:
> 
> the sigma_i value is low?
> for example, all sigma_i values less than 0.5 yield 0 noise when rounded to integers. I think this is ok, but is there some kind of sanity check we should be doing that the calculated sigmas aren't too low in #9 <https://github.com/privcount/privcount/issues/9> ?
This is perfectly fine and indeed expected. The actual value of the noise doesn’t matter, it’s the distribution that the noise was selected from that matters.


> the sigma_i value is high?
> for example, if sigma_i is greater than 252, any sampled noise values between 252 and 253 will be even, any sampled noise values between 253 and 254 will be divisible by 4, and so on. (Doubles have a precision of 253, meaning there are exactly 252 doubles in each interval [2N, 2**(N+1)].) Is this a problem?
> Do we ever intend to sample noise greater than 2**53?
> 
We could conceivably round the noise to be within a certain range (this is the “snapping” method of Mironov), and it shouldn't cause any problems. We are already choosing noise from a distribution (i.e. Gaussian) such that \epsilon-differential privacy is provided with probability 1-\delta, where the privacy fails to be provided when the noise exceeds a certain amount. We could simply “snap” to within that amount. I’m not really sure what happens with large noise values. I would guess that it causes no problem, because any change in values due to one user is either of similar magnitude or is completely lost anyway when added to the noise.

Best,
Aaron

**Comment by teor2345** [comment]
OK, so we actually improved things when we stopped counting in kilobytes? (#)
That's good to know.

I think this is sorted then.
