### ISSUE TITLE
When the TS updates the DC bin widths, what checks need to be performed?

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#75]
@ajohnson-nrl is it still safe to allow the TS to update the DCs bin widths?
If so, do we need to wait for the enforced delay?
(Is it equivalent to a noise weight decrease?)

In general, do we need to check the bins are contiguous?
That is, non-overlapping, no spaces?

Split off #22

**Comment by ajohnson-nrl** [comment]
It is safe to allow the TS to update the DC bin widths. Updating them doesn't force us to wait for the enforced delay because it doesn't change the number of possible inputs to the histogram that could change when a user's behavior changes within the action bounds, and so the same amount of the privacy budget is consumed by that statistic. The bins *must* be non-overlapping to protect privacy (because otherwise a single input can affect multiple bins), but they don't necessarily need to have no spaces.
