### ISSUE TITLE
Can correlations between different counters be used to reveal their values?

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#77]
The values of PrivCount counters are dependent on one another: increased activity on one counter is correlated with increased activity on other counters. Can these correlations be used to break the differential privacy guarantees by removing some of the noise?

For example, what if PrivCount counted cells in, cells out, and cells total? We can use the relationship cells in + cells out = cells total to reveal information about the non-noisy values.

Using actual values:
Cells In: 900 (Actual Value: 1000 - 100 noise)
Cells Out: 900  (Actual Value: 1000 - 100 noise)
Cells Total: 2200 (Actual Value: 2000 + 200 noise)
If this happened, it would reveal that the actual numbers were close to 1000, 1000, and 2000.
Fortunately, the relationships between current PrivCount counters are more complex than subtotals.

I think using bins (and noise for each bin) addresses this issue somewhat.
As does allocating noise based on the expected values of each counter.
But I am not sure whether that is enough to avoid leaking additional information when counter values are combined using known, real-world relationships.

**Comment by ajohnson-nrl** [comment]
There should be no problem with multiple statistics being related. This is accounted for in the differential privacy guarantee. If a single user's activity changes within a bounded amount, we take the worst-case perspective and assume that it could affect each counter simultaneously up to the calculated sensitivity of the statistic. That is why each counter each consumes some of the privacy budget. In your example, enough noise would be added to each summand and to the sum so that the noise makes it hard to tell if a certain amount was included in each summand *even taking the sum into account*.

**Comment by teor2345** [comment]
Thanks, I think I understand now.
