### ISSUE TITLE
Split the PRIVCOUNT event into separate event types in tor

### ISSUE THREAD

**Issue by teor2345** [privcount/privcount#99]
Currently, we have one PRIVCOUNT event, which provides 5 different types of data. We want to modify PrivCount to have a separate event type for each different type of data.

**Comment by robgjansen** [comment]
The new Tor controller events are:

```
PRIVCOUNT_DNS_RESOLVED
PRIVCOUNT_STREAM_BYTES_TRANSFERRED
PRIVCOUNT_STREAM_ENDED
PRIVCOUNT_CIRCUIT_ENDED
PRIVCOUNT_CONNECTION_ENDED
```

The old `PRIVCOUNT` event has been removed.

These are all asynchronous events. Currently, PrivCount does not make use of the DNS event, but I included it anyway for completeness.

This first letter of the old event string used to indicate the event type, i.e., `s` for stream, `c`, for circuit, `t` for connection. Those single letters are now removed from the message since each of these messages already indicate the type of event. The rest of the string that is sent from Tor to PrivCount is unmodified. This means that PrivCount should expect to receive strings will one less token than before.

**Comment by teor2345** [comment]
Rob, you misspelt EnablePrivCount in the commit message for this commit.

**Comment by robgjansen** [comment]
Sorry about that.

**Comment by robgjansen** [comment]
@teor2345 would you like me to force-push an amended commit?

**Comment by teor2345** [comment]
No, force pushing generally makes a mess of other people's repositories that depend on those branches.

Let's document the EnablePrivCount option to tor in the README instead. See #138.
